language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report

addons:
  sonarqube: true
env:
  global:
    - secure: "IoO8MKOB3cH2TWyxqtAHlXsgW0Znh3KffLdcAhur6qLoRCbvRQLp2jD6LiMu1Oxjr/KSHjfZenGaeLqmOcn42a+LEUkXGhjblq0e5KCMJhS/UKtgl6rzY6bog2qF057YhffLyTBj1sdXA5ATIEMijkuQtPPuiWkN5M7Pfu6gkO0mR2MbONjwa/4mrWhp7EVJ39bGQ8vqdZUDJvlmSCTclW57zgQ0y/wNgji9nxCvS6QF/RwBnz0/6XKCFaRPJa9o6hN41JPL8YCGFht2qSQMHO/1srdsy7gyCgDx/UqjnOxrpg5CUmGLO15RVG1alxQiuQ5GEp1e9K9P8iOpNm9T4rwKv3RRF5ZBuNxz2tkl9aYxp/B6N87Jv9Y5lytKXn+G33nttRSp1Zy6X4j7by0Lb+afRWN7AtuzvRGy+cixlQ0+nDWqHf18UHVPAbufL4sDPEaUn6DYDTubnLSDHJm8lMjXN3GwgCOYPE/cfPdJ9lAcRyH9YqjX7AWcncvBf0QRUACdwhJsb2G4cG22f35UK9EFrbI3OyxMyHr4EEweVtgraNySFeEB1oUjpmu5Ys1JOC5dmUq3rAKVFR6Ee2psfoeiyQEfxWNzbESV6ET7WXjKjHhrN151iFu/YZjEy4XIVCnBBMxCnZ33iBypJCrOz4qxpe2atv4yCSI65b82K7M="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
deploy:
  provider: openshift
  user: oltruong
  password:
    secure: WnfVLpBE4MoB2gvM88dUWGQJAagTaJvbsm4EqfDp87qn2dtPChYbwHd1+24ooRN7VK8M8j5RmLsw7mIgK8wwdzY0vxpbSPD3cfTZIpYF5ojvn+Lxiq4tPoQ8IPXm9+cq/vPwT6Otu+zku5On9p/WZ7S8iKJ+jVoiD4cEmZxxyB6SN5xjqh1bWto4zRrWfJJdo1wqnhbvmcmQwc/wXuEbfP2PRunw7uxjiTBFrthTYDztz4+UutiA3uK3XWRwFxAOUDhNMG0CSPBMwVyivI/HHnM+V1/0PpajRHjjS4CVcDEP6UwQbh0AmrmGiItM6IUBS2yrZUFoKHHzzpxN+oeQwJpqFhe7fKgpmyfelrfnMPUSicOOI3fkVUuCpcTnAmzQFCZ5s/xxp3+IMv8qYYf7VZoKzkiwankFIpa+jKC4TRCmBMeZ8H0Lus/d8tHASQAmtMUdCrM51T8RyIvPzJ71t1HbOhhECVCEFNKC3RVFfQS48CIfnM0askvPlbA6tv+nG/9gG8Tr2286LBB+KuFXgvp3ceHCjB+VGsggWE+TTlduJW1/YHjmOBEA1Zq/ZqpC7ViQrL5rWANVKFaZeOfGOIxt8YuYjHZoQFdf2GcpyoXidcHxKapgge/81XfNoVmv2U0ZT3RmsMQ3udP0wSXjQJq3sd4AqGp0GXLOMkVkc0g=
  app: teamag
  domain: nadeva
  on:
    repo: oltruong/teamag
