language: java

jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sonarqube:
      token:
        secure: "qLjSFGq42Agb3VvUYvQKEYMFKqG23vHDWQaM1J8bOSHzH/2basT8YflxRO6G2bH/+o8JAr/649UdZ6tAwqb+70CCdRV6686xjGdQzu5fYitkZfDkUF3AE1bY2yN8vu7FeW4klweVvBstjjbqVYgNd/aOkk7tFTZq8W/KcfKlQVGk3GjqKXYLmL44Ucl28ICnLTAh+Xq49cZ3gKuXmW8LQyxVpnPj/rvbTbSP3+/CUUPmbtGSZ7bENzVCDLVq5w+PAHu+1Imu5dIDDszvxcxR4ESRADFugpkDoY7d2SWm1FTAZwEReBmOAj/McGtOBKPSxIw9BQdVanK5bVv9emJnIovhl6IQeniFj2dP9AxGxjhAldzZiDu+BEnclyEZ7VxEW1cCp/VUL02bBrdjhXZxPStmU6IxPyL48RP/1yIQa10JwT5kCaHaKg68TUMw+V9U4s/LC9maU1I70MEmt4m8IJtCuisYOC8pT5aotF8I3lgCS90AMfovcuqt3CnMl1m2a94s9S0RxNtGTq2Xfvg7XWzjkAqTxDu34iGM3lzV3gPg0cGs1AuM9xq5qCk56WFhlZMN0lWEZdkHWCUbt/maYSxYrn6zilLTCJF+Hf/n944wwRL/ra9Sly1ZR23L0zoEhj6+1y6tvBvFZyAryVuesqg5dT2Fz1Ekd3GMn4g05O4="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
  provider: heroku
  api_key:
    secure: TjmeulSiSHVgTZmKT81wesQWyqklYDGXE35mxhm8MUQW58OwznMGRPE5G3tNjltEyoYbBJSWObw7C96s3x484nCY3AuWUJO5p9u5N6RPSBhQ5RS5lZkqAz/PT0eJkc4PzN7EC0X608Z0u5tAaEdTyzLJZ6alxxsRSGoXy7Z+6jSP3x1Hyb9xokw7aO1cizpItjzZPGJ9gunaifQIVZuFYQeS5LzsrdaM6UVXBlFXR8lC/82ZyaqxHY+Rx4j1ShxO4pW4yfmjqdnM3DzozfxUkU8sZaToSTSy0DA1Syuq8TpkiMa458L7EOFdoH5nZve+Iagkm9UWgzBaDxpZ1lJ+uYvVDF6v3zbn6T9uwhd2lcVwZpmor+BbtaL0g86BBe49tgEHXYDtfYa3eU2rw8ZF0mb+4EujTqnDLLN6yThcPhlESi8INsBg3TvRR5BN1SkWeFTze3dJSJD5AnSAd+zySPQNfJvIGELeGPUJl9ixUDpMgUh1J9KUSENkjVAVamCZdFr/kQ/NMC60TuumZZYpSdXJITSc+eJEoEC4a0SMzIeUX6o+187/9iyLk8wPlyknB3hCkUxtkSaAIkDplVPfRuB1N9JuB9o+MX/svQrXBpv36Rbu4ExKeJnJ6yCU+LYPwF6SGehdkyxpB9Ne40V5pGpRNg0DKfP20GgDWAxqWqg=
